# Generated by Django 4.0.4 on 2022-04-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductNotebook',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('company', models.CharField(max_length=255)),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='ProductTelephone',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('company', models.CharField(max_length=255)),
            ],
            bases=('product.product',),
        ),
    ]
