# Generated by Django 4.0.4 on 2022-04-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productnotebook_producttelephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttelephone',
            name='product_ptr',
        ),
        migrations.DeleteModel(
            name='ProductNotebook',
        ),
        migrations.DeleteModel(
            name='ProductTelephone',
        ),
    ]
