# Generated by Django 4.0.4 on 2022-04-30 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subproducts', to='product.subcategory'),
            preserve_default=False,
        ),
    ]
