# Generated by Django 4.0.4 on 2022-05-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
