# Generated by Django 4.0.4 on 2022-05-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_comments_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='product',
        ),
        migrations.AddField(
            model_name='comments',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to='product.product'),
        ),
    ]
