# Generated by Django 4.0.4 on 2022-05-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_remove_comments_product_comments_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='comment', to='product.comments'),
        ),
    ]
