# Generated by Django 4.0.4 on 2022-05-28 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_remove_comments_product_product_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='comments',
        ),
    ]
