# Generated by Django 4.0.4 on 2022-05-29 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_manufacturer_options_manufacturer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={},
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='created_at',
        ),
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
