# Generated by Django 4.0.4 on 2023-05-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='description',
        ),
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default='none'),
        ),
    ]
